---
  - name: create unit file
    gather_facts: false
    hosts: otus
    become: true
    become_method: sudo
    tasks:
      - name: Install spawn-fcgi
        apt:
          name:
            - spawn-fcgi
            - php
            - php-cli
            - php-cgi
            - libapache2-mod-fcgid
            - apache2
      - name: Copy spawn-fcgi
        copy:
          src: spawn-fcgi
          dest: /etc/default/spawn-fcgi
      - name: Copy spawn-fcgi.service
        copy:
          src: spawn-fcgi.service
          dest: /etc/systemd/system/spawn-fcgi.service
      - name: start service
        systemd:
          daemon_reload: true
          name: spawn-fcgi.service
          state: started

      - name: Check service
        ansible.builtin.systemd:
          name: "spawn-fcgi.service"
        register: output
      - debug:
          var: output.status.ActiveState